#ifndef CONFIG_HEADER 
#define CONFIG_HEADER 

#include <Arduino.h>

#define LIGHT_RELAY_DIGITAL_PIN 2
//TODO
#define LIQUID_TEMPERATURE_SENSOR_DIGITAL_PIN 3
#define WATER_LEVEL_POWER_DIGITAL_PIN 4

#define WATER_LEVEL_SIGNAL_ANALOG_PIN A0

#define LIGHT_ON_START_HOUR 8
#define LIGHT_ON_END_HOUR 20

#define DELAY_APP_SECONDS 60

#endif

