#ifndef CONFIG_HEADER 
#define CONFIG_HEADER 

#include <Arduino.h>

#define LIGHT_DIGITAL_PIN 2
#define LIQUID_TEMPERATURE_DIGITAL_PIN 3
#define WATER_LEVEL_POWER_DIGITAL_PIN 4
#define WATER_PUMP_DIGITAL_PIN 5
#define AIR_SENSOR_DIGITAL_PIN 6

#define SD_CS_DIGITAL_PIN 53

#define WATER_LEVEL_SIGNAL_ANALOG_PIN A0

#define LIGHT_ON_START_HOUR 8
#define LIGHT_ON_END_HOUR 20

#define DELAY_APP_SECONDS 60

#define PUMP_WATER_ON_START_HOUR_1 8
#define PUMP_WATER_ON_START_HOUR_2 16
#define PUMP_WATER_ON_DURATION_MINUTES 5

#endif

